import { type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { gods } from '../schema/tables';

const GOD_SEED_DATA = [
  {
    id: 'aurvandos',
    name: 'Aurvandos',
    title: 'The Unyielding',
    domain: 'Duty, protection, endurance, martial honor',
    philosophy: 'WARDEN',
    churchName: 'The Order of the Unbroken Shield',
    churchDescription: 'A hierarchical, disciplined order that values duty above all. Followers sacrifice personal comfort for communal protection.',
    racialLean: 'Dwarves, militaristic Humans, Frost Drakonid',
    iconName: 'shield',
    colorHex: '#6B8FBF',
    sortOrder: 1,
  },
  {
    id: 'veradine',
    name: 'Veradine',
    title: 'The Weigher of Costs',
    domain: 'Sacrifice, pragmatism, governance, difficult choices',
    philosophy: 'PRAGMATIST',
    churchName: 'The Conclave of the Balanced Scale',
    churchDescription: 'A meritocratic and political conclave that embeds in governance structures, pushing for rational policy over idealism.',
    racialLean: 'Humans, Harthfolk, political factions everywhere',
    iconName: 'scale',
    colorHex: '#C4A35A',
    sortOrder: 2,
  },
  {
    id: 'tyrvex',
    name: 'Tyrvex',
    title: 'The Unmaker',
    domain: 'Knowledge, ambition, arcane power, transformation',
    philosophy: 'RECLAIMER',
    churchName: 'The Crucible of the Seeking Flame',
    churchDescription: 'Part church, part research institution. Academic, secretive, and elitist — they guard dangerous knowledge others would destroy.',
    racialLean: 'Nethkin, Gnomes, scholarly Elves, Crystal Drakonid',
    iconName: 'flame',
    colorHex: '#D4553A',
    sortOrder: 3,
  },
  {
    id: 'xolthira',
    name: "Xol'Thira",
    title: 'The Dissolved',
    domain: 'Transformation, entropy, mysticism, the void',
    philosophy: 'EMBRACED',
    churchName: 'The Communion of the Threshold',
    churchDescription: 'Not a church in the traditional sense — mystic circles and visionaries loosely connected by shared transcendent experience.',
    racialLean: 'Revenants, Changelings, Nethkin scholars',
    iconName: 'eye',
    colorHex: '#8B5CF6',
    sortOrder: 4,
  },
  {
    id: 'kethara',
    name: 'Kethara',
    title: 'The Reluctant',
    domain: 'Mercy, healing, grief, compassion',
    philosophy: 'PRAGMATIST',
    churchName: 'The Sisterhood of Gentle Hands',
    churchDescription: 'Healers, counselors, and caregivers. The most universally respected church — helps everyone regardless of faction.',
    racialLean: 'Broadly popular across all races, especially Half-Elves and Half-Orcs',
    iconName: 'heart-handshake',
    colorHex: '#F9A8D4',
    sortOrder: 5,
  },
  {
    id: 'vareth',
    name: 'Vareth',
    title: 'The Walled',
    domain: 'Borders, self-reliance, protection of kin, exclusion',
    philosophy: 'WITHDRAWN',
    churchName: 'The Covenant of Hearth and Wall',
    churchDescription: 'Insular and community-focused, deeply suspicious of outsiders. The church of nationalism and localism.',
    racialLean: 'Dwarves, Orcs, Frost Drakonid',
    iconName: 'brick-wall',
    colorHex: '#92400E',
    sortOrder: 6,
  },
  {
    id: 'solimene',
    name: 'Solimene',
    title: 'The Undecided',
    domain: 'Balance, deliberation, law, neutrality',
    philosophy: 'PRAGMATIST',
    churchName: 'The Court of Even Measure',
    churchDescription: 'Judges, arbiters, and record-keepers. They operate courts and mediate disputes, refusing to take sides.',
    racialLean: 'Half-Elves, scholarly types, Harthfolk',
    iconName: 'gavel',
    colorHex: '#94A3B8',
    sortOrder: 7,
  },
  {
    id: 'tessivane',
    name: 'Tessivane',
    title: 'The Smiling Shadow',
    domain: 'Fortune, trickery, adaptability, survival',
    philosophy: 'PRAGMATIST',
    churchName: 'The Fellowship of the Silver Tongue',
    churchDescription: 'More mutual aid society than church. No temples — back rooms and tavern booths. Services look like social gatherings.',
    racialLean: 'Harthfolk, Nethkin, Changelings, Storm Drakonid',
    iconName: 'smile',
    colorHex: '#10B981',
    sortOrder: 8,
  },
  {
    id: 'valtheris',
    name: 'Valtheris',
    title: 'The Bridge-Builder',
    domain: 'Unity, cooperation, communication, hope',
    philosophy: 'UNITER',
    churchName: 'The Accord of the Open Hand',
    churchDescription: 'The most ecumenical church — seeks interfaith dialogue and believes all twelve gods are necessary for Aethermere.',
    racialLean: 'Half-Elves, cosmopolitan Humans, Storm Drakonid',
    iconName: 'handshake',
    colorHex: '#38BDF8',
    sortOrder: 9,
  },
  {
    id: 'domakhar',
    name: 'Domakhar',
    title: 'The Iron Crown',
    domain: 'Authority, order, law through strength, empire',
    philosophy: 'WARDEN',
    churchName: 'The Mandate of the Iron Crown',
    churchDescription: 'Authoritarian and unapologetically power-focused. Believes in strong rulers, strict laws, and decisive leadership.',
    racialLean: 'Ambitious Human nobles, Orc war-chiefs, Flame Drakonid',
    iconName: 'crown',
    colorHex: '#F59E0B',
    sortOrder: 10,
  },
  {
    id: 'morvaine',
    name: 'Morvaine',
    title: 'The Hollow',
    domain: 'Truth, disillusionment, entropy, endings',
    philosophy: 'NIHILIST',
    churchName: 'The Ashen Witness',
    churchDescription: 'Fatalists and truth-tellers who expose cracks in every system. Uncomfortable to be around, but often right.',
    racialLean: 'Revenants, disillusioned veterans, Nethkin scholars',
    iconName: 'eye-off',
    colorHex: '#6B7280',
    sortOrder: 11,
  },
  {
    id: 'seraphiel',
    name: 'Seraphiel',
    title: 'The Grieving',
    domain: 'Loss, memory, vengeance, bittersweet beauty',
    philosophy: 'WARDEN',
    churchName: 'The Choir of Ashes',
    churchDescription: 'Part memorial society, part revenge cult. Guardians of historical memory who believe the world owes a debt that can never be repaid.',
    racialLean: 'Dwarves, Half-Orcs, anyone who has lost something and cannot let go',
    iconName: 'book-open',
    colorHex: '#A855F7',
    sortOrder: 12,
  },
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function seedReligion(db: NodePgDatabase<any>) {
  console.log('  Seeding gods (12 deities)...');

  for (const god of GOD_SEED_DATA) {
    await db.insert(gods).values(god).onConflictDoUpdate({
      target: gods.id,
      set: {
        name: god.name,
        title: god.title,
        domain: god.domain,
        philosophy: god.philosophy,
        churchName: god.churchName,
        churchDescription: god.churchDescription,
        racialLean: god.racialLean,
        iconName: god.iconName,
        colorHex: god.colorHex,
        sortOrder: god.sortOrder,
      },
    });
  }

  console.log(`  ✓ ${GOD_SEED_DATA.length} gods seeded`);
}
