import { Router } from 'express';
import authRouter from './auth';
import characterRouter from './characters';
import profilesRouter from './profiles';
import worldRouter from './world';
import townsRouter from './towns';
import travelRouter from './travel';
import marketRouter from './market';
import workRouter from './work';
import craftingRouter from './crafting';
import combatPveRouter from './combat-pve';
import combatPvpRouter from './combat-pvp';
import electionsRouter from './elections';
import governanceRouter from './governance';
import guildRouter from './guilds';
import messagesRouter from './messages';
import friendsRouter from './friends';
import notificationsRouter from './notifications';
import questsRouter from './quests';
import skillsRouter from './skills';
import professionsRouter from './professions';
import toolsRouter from './tools';
import equipmentRouter from './equipment';
import itemsRouter from './items';
import buildingsRouter from './buildings';
import tradeAnalyticsRouter from './trade-analytics';
import caravansRouter from './caravans';
import racesRouter from './races';
import zonesRouter from './zones';
import regionsRouter from './regions';
import diplomacyRouter from './diplomacy';
import petitionsRouter from './petitions';
import worldEventsRouter from './world-events';
import specialMechanicsRouter from './special-mechanics';
import foodRouter from './food';
import actionsRouter from './actions';
import reportsRouter from './reports';
import adminRouter from './admin';
import serviceRouter from './service';
import loanRouter from './loans';
import gameRoutes from './game';
import gatheringRouter from './gathering';
import partiesRouter from './parties';

const router = Router();

router.use('/auth', authRouter);
// Profile search + profile by ID registered before generic character :id route
router.use('/characters', profilesRouter);
router.use('/characters', characterRouter);
router.use('/world', worldRouter);
router.use('/towns', townsRouter);
router.use('/travel', travelRouter);
router.use('/market', marketRouter);
router.use('/work', workRouter);
router.use('/gathering', gatheringRouter);
router.use('/crafting', craftingRouter);
router.use('/combat/pve', combatPveRouter);
router.use('/combat/pvp', combatPvpRouter);
router.use('/elections', electionsRouter);
router.use('/governance', governanceRouter);
router.use('/guilds', guildRouter);
router.use('/messages', messagesRouter);
router.use('/friends', friendsRouter);
router.use('/notifications', notificationsRouter);
router.use('/quests', questsRouter);
router.use('/skills', skillsRouter);
router.use('/professions', professionsRouter);
router.use('/tools', toolsRouter);
router.use('/equipment', equipmentRouter);
router.use('/items', itemsRouter);
router.use('/buildings', buildingsRouter);
router.use('/trade', tradeAnalyticsRouter);
router.use('/caravans', caravansRouter);
router.use('/races', racesRouter);
router.use('/zones', zonesRouter);
router.use('/regions', regionsRouter);
router.use('/diplomacy', diplomacyRouter);
router.use('/petitions', petitionsRouter);
router.use('/world-events', worldEventsRouter);
router.use('/special-mechanics', specialMechanicsRouter);
router.use('/food', foodRouter);
router.use('/actions', actionsRouter);
router.use('/reports', reportsRouter);
router.use('/admin', adminRouter);
router.use('/service', serviceRouter);
router.use('/loans', loanRouter);
router.use('/game', gameRoutes);
router.use('/parties', partiesRouter);

export default router;
